[package]
name = "calendar-data"
version = "0.1.0"
edition = "2021"

[dependencies]
calendar-core = { path = "../calendar-core" }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
